parameters:
    env(ADMIN_PASSWORD): '$2y$12$pu1i1/VoBkr/JZztTip8s.7//0b2U3C2b94trectvXg/eJxRQ7WUi'

security:
    providers:
        in_memory:
            memory:
                users:
                    admin:
                        password: '%env(ADMIN_PASSWORD)%'
                        roles: 'ROLE_ADMIN'
    encoders:
        Symfony\Component\Security\Core\User\User:
            algorithm: bcrypt
            cost: 12
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: true
            http_basic: true
    access_control:
         - { path: ^/answers, roles: ROLE_ADMIN }
