version: '3'

services:
    quena_nginx:
        image: zelton/quena-nginx:1.0
        container_name: quena_nginx_prod
        restart: always
        ports:
            - "80:8080"
    quena_php:
        image: zelton/quena-php:1.0
        container_name: quena_php_prod
        restart: always
        environment:
            - APP_ENV=prod
            - APP_SECRET=38cf2f1d1c90c5082e82227e2d975d1c
            # default password 'admin', you can generate a different one with bin/console security:encode-password
            # remember to escape all the dollar signs with another one
            - ADMIN_PASSWORD=$$2y$$12$$pu1i1/VoBkr/JZztTip8s.7//0b2U3C2b94trectvXg/eJxRQ7WUi
            - CORS_ALLOW_ORIGIN=https://quena.yourdomain.com
            - DATABASE_URL=sqlite:///%kernel.project_dir%/var/data.db
            - TZ=Europe/Warsaw
        volumes:
            - data:/var/www/var

volumes:
    data:
