version: '3'

services:
    quena_nginx:
        image: zelton/quena-nginx:1.0
        container_name: quena_nginx_dev
        ports:
            - "8000:8080"
        volumes:
            - ./public:/var/www/public
    quena_php:
        image: zelton/quena-php:1.0
        container_name: quena_php_dev
        volumes:
            - .:/var/www
